# Generated by Django 5.2.7 on 2025-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScreenRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="recordings/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
