# Generated by Django 5.2.7 on 2025-10-18 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recordings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("s3_key", models.CharField(max_length=1024)),
                (
                    "s3_upload_id",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("part_size", models.IntegerField(default=5242880)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("aborted", "Aborted"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.IntegerField()),
                ("etag", models.CharField(blank=True, max_length=512, null=True)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="recordings.uploadsession",
                    ),
                ),
            ],
            options={
                "unique_together": {("upload", "part_number")},
            },
        ),
    ]
